name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          export CLASSPATH=/usr/java/bin
          git checkout indev
          cd ./src/ZReadmeGenerator
          javac ReadmeGenerator.java
          cd ~
          ls